arb-dir: lib/app/localization/arb
template-arb-file: app_en.arb
output-dir: lib/app/localization/gen
output-localization-file: app_localizations_gen.dart
output-class: AppLocalizations
nullable-getter: false
